# This rule is not used by the project ha-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.ha.example.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ha-operator
    app.kubernetes.io/managed-by: kustomize
  name: highavailabilityapp-editor-role
rules:
- apiGroups:
  - apps.ha.example.ai
  resources:
  - highavailabilityapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ha.example.ai
  resources:
  - highavailabilityapps/status
  verbs:
  - get
