apiVersion: apps.ha.example.ai/v1alpha1
kind: HighAvailabilityApp
metadata:
  labels:
    app.kubernetes.io/name: ha-operator
    app.kubernetes.io/managed-by: kustomize
  name: highavailabilityapp-sample
spec:
  # TODO(user): Add fields here
